# Generated by Django 2.0.3 on 2019-07-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praia', '0005_astrometryinput_error_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometryinput',
            name='execution_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Execution Time'),
        ),
        migrations.AddField(
            model_name='astrometryinput',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish Time'),
        ),
        migrations.AddField(
            model_name='astrometryinput',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
